language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
cache: pip
install:
  - pip install requests
  - pip install tqdm
script:
  - python tests/test_api.py
  - python tests/test_mailbox.py
  - python tests/test_util.py